package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "tensor_square_conjecture",
    srcs = ["tensor_square_conjecture.cc"],
    deps = [
        "//combinatorics:partition",
        "//symmetric_group:character",
        "@com_google_absl//absl/types:span",
    ],
)
